export const MOCK_INSTRUMENTS = [
    {
        symbol: "INDSHOP",
        name: "India Shopping REIT",
        type: "REIT",
        lastPrice: 237.5,
        change: -1.15,
        changePercent: -0.48,
        volume: 154200,
        yield: 5.2,
        marketCap: 45000000000,
    },
    {
        symbol: "LOGEIT",
        name: "Logistics EIT Trust",
        type: "EIT",
        lastPrice: 412.0,
        change: 4.55,
        changePercent: 1.12,
        volume: 89300,
        yield: 6.8,
        marketCap: 32000000000,
    },
    {
        symbol: "OFFICER",
        name: "Prime Office REIT",
        type: "REIT",
        lastPrice: 315.2,
        change: 1.2,
        changePercent: 0.38,
        volume: 210500,
        yield: 5.9,
        marketCap: 58000000000,
    },
    {
        symbol: "DATAINF",
        name: "Data Infra Trust",
        type: "EIT",
        lastPrice: 189.4,
        change: -0.8,
        changePercent: -0.42,
        volume: 305000,
        yield: 7.1,
        marketCap: 28000000000,
    },
    {
        symbol: "RETAILR",
        name: "Retail Assets REIT",
        type: "REIT",
        lastPrice: 156.8,
        change: 0.0,
        changePercent: 0.0,
        volume: 95000,
        yield: 6.2,
        marketCap: 19000000000,
    },
];

export const MARKET_SNAPSHOT = {
    totalMarketCap: "₹1.82T",
    avgYield: "6.24%",
    volatilityIndex: "14.2",
    topGainers: MOCK_INSTRUMENTS.filter(i => i.change > 0),
    topLosers: MOCK_INSTRUMENTS.filter(i => i.change < 0),
};
